extends RefCounted

# Generated by tools/audit_progression_graph.py from config/progression_contract.json.
# Edit the JSON contract, then run the audit with --write.
const CANONICAL_START_MAP_ID := "production_slice_01"
const CANONICAL_START_ENTRY_ID := "surface_boat_entry"
const SALVAGE_SCORE_BY_TIER := {"common": 100, "valuable": 300}
const OXYGEN_TANK_UPGRADE_ID := "oxygen_tank_1"
const OXYGEN_TANK_UPGRADE_COST := 500
const CARGO_CAPACITY_UPGRADE_ID := "cargo_pouch_1"
const CARGO_CAPACITY_UPGRADE_COST := 700
const SCANNER_CAPABILITY_ID := "survey_scanner_1"
const DIVE_LIGHT_CAPABILITY_ID := "dive_light_1"
