#!/usr/bin/env python3
"""Authored gameplay source records shared by production slice 01 consumers."""

from __future__ import annotations

from production_slice_01_expansions import (
    biological_resource_sources,
    daily_conditions,
    expansion_entities,
    expansion_survey_targets,
    expansion_zones,
    hostile_encounters,
    material_candidate_pools,
    material_projects,
    moving_hazards,
    progression_containers,
)
from production_slice_01_player_gate_correction import behavioral_guarded_cache


def gameplay_sections(
    entry: tuple[int, int], slice_bounds: dict[str, int], boat_width: int
) -> dict:
    """Return ordered, slice-local gameplay sections for generated map assembly."""
    return {
        "zones": [
            {
                "id": "production_slice_bounds",
                "type": "marker",
                "x": 0,
                "y": 0,
                "w": slice_bounds["w"],
                "h": slice_bounds["h"],
                "intent": "Full extent of the first production slice crop.",
            },
            {
                "id": "entry_shaft_route",
                "type": "marker",
                "x": 28,
                "y": 0,
                "w": 24,
                "h": 25,
                "intent": "Top-water descent from boat entry into the first branch.",
            },
            {
                "id": "central_crossing_route",
                "type": "marker",
                "x": 24,
                "y": 22,
                "w": 37,
                "h": 22,
                "intent": "Primary branching hub with a return route toward the boat.",
            },
            {
                "id": "lower_loop_route",
                "type": "marker",
                "x": 12,
                "y": 55,
                "w": 52,
                "h": 24,
                "intent": "Lower optional loop for a longer salvage return test.",
            },
            {
                "id": "lower_left_loop_connector",
                "type": "marker",
                "x": 2,
                "y": 74,
                "w": 4,
                "h": 4,
                "world_connector": True,
                "connector_label": "Lower-left relay",
                "destination_map_id": "production_slice_04",
                "destination_map_path": "res://maps/production_slice_04.greybox.json",
                "destination_entry_id": "relay_sub_entry",
                "connector_direction": "forward",
                "intent": "Optional advanced-current entrance; not part of the fins, scanner, or weapon progression chain.",
            },
            *expansion_zones(),
            {
                "id": "deep_cache_first_step_cue",
                "type": "marker",
                "x": 28,
                "y": 58,
                "w": 4,
                "h": 3,
                "objective_step_cue": True,
                "objective_id": "deep_cache_route_objective",
                "target_id": "salvage_lower_loop",
                "route_context": "deep_cache_commitment",
                "objective_step_label": "Lower loop",
                "intent": "Opening relay-trail objective cue for its first required target.",
            },
            {
                "id": "return_pressure_to_boat",
                "type": "marker",
                "x": 12,
                "y": 50,
                "w": 28,
                "h": 18,
                "intent": (
                    "Pass 10 return-pressure segment around salvage_return_branch "
                    "where full cargo should prompt banking at the boat."
                ),
            },
            {
                "id": "lower_loop_oxygen_rest_pocket",
                "type": "marker",
                "x": 27,
                "y": 60,
                "w": 8,
                "h": 5,
                "route_context": "oxygen_rest_pressure",
                "oxygen_rest": True,
                "oxygen_rest_label": "Rest pocket",
                "oxygen_rest_cap_seconds": 45,
                "oxygen_rest_refill_per_second": 8,
                "intent": "Pass 12 limited oxygen rest pocket in the lower-loop return corridor; supports a brief in-cave oxygen decision without changing extraction, cargo, salvage, hazards, or terrain topology.",
            },
            {
                "id": "southwest_return_pocket_extension",
                "type": "marker",
                "x": 1,
                "y": 67,
                "w": 27,
                "h": 16,
                "intent": (
                    "Pass 08/09 route segment marking the lower-left return pocket "
                    "near salvage_return_branch for a small optional detour decision."
                ),
            },
            {
                "id": "southwest_pocket_pre_pickup_cue",
                "type": "marker",
                "x": 12,
                "y": 65,
                "w": 16,
                "h": 9,
                "route_cue_id": "southwest_pocket_pre_pickup_cue",
                "cue_target_id": "salvage_southwest_return_cache",
                "cue_text": "Relay trail cache ahead",
                "cue_condition": "target_uncollected",
                "intent": "Pre-pickup route cue for the required non-eel relay-trail payoff.",
            },
            {
                "id": "lower_loop_to_deep_cache_pressure",
                "type": "marker",
                "x": 54,
                "y": 64,
                "w": 13,
                "h": 13,
                "intent": (
                    "Pass 07 hazard/navigation pressure segment covering the hazard_right_branch "
                    "warning corridor and approach to timed salvage_deep_right_cache."
                ),
            },
            {
                "id": "deep_cache_dark_pocket",
                "type": "marker",
                "x": 50,
                "y": 68,
                "w": 16,
                "h": 11,
                "visibility_zone": True,
                "visibility_level": "dark",
                "visibility_label": "Dark pocket",
                "route_context": "deep_cache_pressure",
                "required_upgrade_id": "dive_light_1",
                "visual_only": True,
                "intent": "First visual-only darkness pressure zone around the lower-loop-to-deep-cache route.",
            },
        ],
        "daily_conditions": daily_conditions(),
        "progression_containers": progression_containers(),
        "moving_hazards": [
            {
                "id": "deep_route_jellyfish_patrol",
                "kind": "jellyfish",
                "x": 54,
                "y": 68,
                "movement": "linear_patrol",
                "path": [{"x": 54, "y": 68}, {"x": 64, "y": 68}],
                "speed_tiles_per_second": 1.0,
                "route_context": "deep_cache_pressure",
                "display_label": "Jellyfish patrol",
                "intent": "First deterministic moving hazard on the lower-loop to deep-cache route.",
            },
            *moving_hazards(),
        ],
        "hostile_encounters": hostile_encounters(),
        "biological_resource_sources": biological_resource_sources(),
        "route_objectives": [
            {
                "id": "deep_cache_route_objective",
                "route_context": "deep_cache_commitment",
                "label": "Relay trail",
                "required_banked_targets": [
                    "salvage_lower_loop",
                    "salvage_southwest_return_cache",
                ],
                "supporting_marker_ids": [
                    "lower_loop_route",
                    "deep_cache_first_step_cue",
                    "southwest_return_pocket_extension",
                    "southwest_pocket_pre_pickup_cue",
                    "lower_loop_oxygen_rest_pocket",
                    "return_pressure_to_boat",
                ],
                "intent": "Opening objective banks two non-eel lower-loop payoffs and points toward the lower-left relay before the shock-prod-gated deep-right cache.",
            }
        ],
        "primary_route_objective_id": "deep_cache_route_objective",
        "next_dive_objective_prompts": [
            {
                "id": "deep_cache_next_dive_prompt",
                "trigger": "primary_objective_complete",
                "objective_id": "deep_cache_route_objective",
                "target_id": "upper_right_current_pocket_gate",
                "label": "Next dive: Investigate east current",
                "route_context": "upper_right_current_pocket",
                "intent": "Result prompt pointing the next dive toward the standard current crossed passively with propulsion fins.",
            }
        ],
        "survey_targets": expansion_survey_targets(),
        "material_candidate_pools": material_candidate_pools(),
        "material_projects": material_projects(),
        "background": [
            {
                "id": "distant_entry_wall",
                "type": "background",
                "x": 30,
                "y": 6,
                "w": 18,
                "h": 22,
            },
            {
                "id": "distant_crossing_mass",
                "type": "background",
                "x": 28,
                "y": 24,
                "w": 30,
                "h": 24,
            },
            {
                "id": "distant_lower_loop",
                "type": "background",
                "x": 14,
                "y": 58,
                "w": 44,
                "h": 18,
            },
        ],
        "entities": [
            {
                "id": "surface_boat_entry",
                "type": "boat_spawn",
                "x": entry[0],
                "y": entry[1],
                "w": boat_width,
                "h": 1,
                "entry_x": entry[0],
                "entry_y": entry[1],
                "facing": "right",
                "intent": "Top-water boat entry and extraction marker for the first production slice.",
            },
            {
                "id": "salvage_entry_shaft",
                "type": "salvage",
                "x": 38,
                "y": 18,
                "kind": "crate",
                "route_choice_id": "safe_entry_pickup",
                "validation_route": "safe_route_choice",
                "route_order": 0,
                "intent": "Safe route target near the entry shaft for short collect-return comparison.",
            },
            {
                "id": "salvage_center_crossing",
                "type": "salvage",
                "x": 46,
                "y": 30,
                "kind": "wreck_fragment",
            },
            {
                "id": "salvage_right_branch",
                "type": "salvage",
                "x": 64,
                "y": 24,
                "kind": "crate",
            },
            {
                "id": "salvage_lower_loop",
                "type": "salvage",
                "x": 30,
                "y": 67,
                "kind": "relic",
                "tier": "valuable",
                "route_choice_id": "lower_loop_payoff",
                "validation_route": "expanded_route_choice",
                "route_order": 0,
                "intent": "Route-choice payoff target for the lower optional loop.",
            },
            {
                "id": "salvage_pry_locker",
                "type": "salvage",
                "x": 36,
                "y": 64,
                "kind": "crate",
                "tier": "valuable",
                "interaction": "pry_salvage",
                "interaction_seconds": 1.2,
                "pry_stages": 3,
                "interaction_label": "sealed cache",
                "route_choice_id": "lower_bend_pry_detour",
                "validation_route": "pry_salvage_detour",
                "route_order": 0,
                "intent": "Pass 17 optional pry target near the lower-bend hazard, adding a deliberate oxygen-time spend without changing topology.",
            },
            behavioral_guarded_cache(),
            {
                "id": "salvage_southwest_return_cache",
                "type": "salvage",
                "x": 25,
                "y": 76,
                "kind": "crate",
                "tier": "valuable",
                "route_choice_id": "southwest_pocket_detour",
                "validation_route": "southwest_pocket_decision",
                "route_order": 0,
                "intent": (
                    "Non-eel valuable payoff completing the opening relay trail; keeps instant collection "
                    "while the separate material route supplies the propulsion-fins recipe."
                ),
            },
            {
                "id": "salvage_return_branch",
                "type": "salvage",
                "x": 17,
                "y": 58,
                "kind": "crate",
                "route_choice_id": "return_branch_bank_prompt",
                "validation_route": "return_pressure_decision",
                "route_order": 0,
                "intent": "Pass 10 return-pressure pickup that should remain available while full cargo returns to the boat.",
            },
            {
                "id": "hazard_shaft_choke",
                "type": "hazard",
                "x": 34,
                "y": 20,
                "kind": "jellyfish",
            },
            {
                "id": "hazard_crossing_choke",
                "type": "hazard",
                "x": 52,
                "y": 34,
                "kind": "mine",
            },
            {
                "id": "hazard_lower_bend",
                "type": "hazard",
                "x": 36,
                "y": 61,
                "kind": "jellyfish",
            },
            {
                "id": "hazard_right_branch",
                "type": "hazard",
                "x": 57,
                "y": 66,
                "kind": "mine",
            },
            *expansion_entities(),
        ],
        "camera_tests": [
            {
                "id": "production_slice_overview",
                "center_x": 36,
                "center_y": 42,
                "zoom": 0.36,
                "intent": "Broad production-slice context with reduced side border.",
            },
            {
                "id": "production_slice_entry_shaft",
                "center_x": 39,
                "center_y": 11,
                "zoom": 0.66,
                "intent": "Boat entry, surface opening, and first descent read.",
            },
            {
                "id": "production_slice_first_route_choice",
                "center_x": 42,
                "center_y": 25,
                "zoom": 0.60,
                "intent": "First route choice after the entry shaft, with nearby salvage and hazard.",
            },
            {
                "id": "production_slice_central_crossing",
                "center_x": 48,
                "center_y": 43,
                "zoom": 0.58,
                "intent": "Central branching, nearby salvage, and hazard pressure review.",
            },
            {
                "id": "production_slice_lower_loop",
                "center_x": 36,
                "center_y": 66,
                "zoom": 0.58,
                "intent": "Lower optional route and return-path readability review.",
            },
            {
                "id": "production_slice_return_to_boat",
                "center_x": 36,
                "center_y": 18,
                "zoom": 0.46,
                "intent": "Return path context from first branch back to boat extraction.",
            },
        ],
        "review_questions": [
            "Does the top-water boat entry read as the start and extraction point?",
            "Do the central crossing and lower loop feel like meaningful route choices?",
            "Are salvage and hazard markers placed where they create pressure without clutter?",
            "Do sealed slice edges feel like natural cave boundaries rather than arbitrary cutoffs?",
        ],
    }
