#!/usr/bin/env python3
"""Load the canonical runtime-only progression contract and render GDScript constants."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "config" / "progression_contract.json"
GENERATED_GDSCRIPT_PATH = ROOT / "scripts" / "main" / "progression_contract.gd"
ID_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
CONSTANT_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")


def load_contract(path: Path = CONTRACT_PATH) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"Could not load progression contract {path}: {exc}") from exc
    failures = validate_contract(payload)
    if failures:
        raise ValueError("Invalid progression contract:\n- " + "\n- ".join(failures))
    return payload


def validate_contract(payload: Any) -> list[str]:
    if not isinstance(payload, dict):
        return ["root must be an object"]
    failures: list[str] = []
    if payload.get("version") != 1:
        failures.append("version must equal 1")
    start = payload.get("canonical_start")
    if not isinstance(start, dict):
        failures.append("canonical_start must be an object")
    else:
        _require_id(start.get("map_id"), "canonical_start.map_id", failures)
        _require_id(start.get("entry_id"), "canonical_start.entry_id", failures)
    scores = payload.get("salvage_score_by_tier")
    if not isinstance(scores, dict) or not scores:
        failures.append("salvage_score_by_tier must be a non-empty object")
    else:
        for tier, score in scores.items():
            _require_id(tier, "salvage score tier", failures)
            if not _positive_int(score):
                failures.append(f"salvage score for {tier!r} must be a positive integer")

    seen_ids: set[str] = set()
    seen_constants: set[str] = set()
    purchase_collections = {"session_upgrades", "durable_purchases"}
    for collection_name in ("session_upgrades", "durable_capabilities", "durable_purchases"):
        items = payload.get(collection_name)
        if not isinstance(items, list):
            failures.append(f"{collection_name} must be an array")
            continue
        for index, item in enumerate(items):
            label = f"{collection_name}[{index}]"
            if not isinstance(item, dict):
                failures.append(f"{label} must be an object")
                continue
            item_id = _require_id(item.get("id"), f"{label}.id", failures)
            constant_name = item.get("constant_name")
            if not isinstance(constant_name, str) or not CONSTANT_PATTERN.fullmatch(constant_name):
                failures.append(f"{label}.constant_name must be UPPER_SNAKE_CASE")
            if item_id in seen_ids:
                failures.append(f"duplicate progression purchase id {item_id!r}")
            if isinstance(constant_name, str) and constant_name in seen_constants:
                failures.append(f"duplicate progression constant name {constant_name!r}")
            seen_ids.add(item_id)
            if isinstance(constant_name, str):
                seen_constants.add(constant_name)
            if collection_name in purchase_collections and not _positive_int(item.get("cost")):
                failures.append(f"{label}.cost must be a positive integer")
            if not isinstance(item.get("mandatory"), bool):
                failures.append(f"{label}.mandatory must be boolean")
            if collection_name == "durable_capabilities":
                unsupported = sorted(set(item) - {"id", "constant_name", "mandatory"})
                if unsupported:
                    failures.append(f"{label} has unsupported ownership fields {unsupported}")
            for field in ("purchase_map_id", "purchase_entry_id", "required_lead_source_id"):
                if field in item:
                    _require_id(item.get(field), f"{label}.{field}", failures)
            for field in ("funding_source_ids", "unlocks_target_ids"):
                if field in item:
                    _require_id_list(item.get(field), f"{label}.{field}", failures)
    return failures


def render_gdscript(contract: dict[str, Any]) -> str:
    start = contract["canonical_start"]
    lines = [
        "extends RefCounted",
        "",
        "# Generated by tools/audit_progression_graph.py from config/progression_contract.json.",
        "# Edit the JSON contract, then run the audit with --write.",
        f'const CANONICAL_START_MAP_ID := "{start["map_id"]}"',
        f'const CANONICAL_START_ENTRY_ID := "{start["entry_id"]}"',
        f"const SALVAGE_SCORE_BY_TIER := {_gd_dictionary(contract['salvage_score_by_tier'])}",
    ]
    for item in contract["session_upgrades"]:
        prefix = item["constant_name"]
        lines.append(f'const {prefix}_UPGRADE_ID := "{item["id"]}"')
        lines.append(f"const {prefix}_UPGRADE_COST := {item['cost']}")
    for item in contract["durable_capabilities"]:
        prefix = item["constant_name"]
        lines.append(f'const {prefix}_CAPABILITY_ID := "{item["id"]}"')
    for item in contract["durable_purchases"]:
        prefix = item["constant_name"]
        lines.append(f'const {prefix}_CAPABILITY_ID := "{item["id"]}"')
        lines.append(f"const {prefix}_COST := {item['cost']}")
        lines.append(f'const {prefix}_PURCHASE_MAP_ID := "{item["purchase_map_id"]}"')
        lines.append(f'const {prefix}_PURCHASE_ENTRY_ID := "{item["purchase_entry_id"]}"')
        lines.append(f'const {prefix}_LEAD_SOURCE_ID := "{item["required_lead_source_id"]}"')
    return "\n".join(lines) + "\n"


def generated_contract_failure(contract: dict[str, Any], path: Path = GENERATED_GDSCRIPT_PATH) -> str:
    expected = render_gdscript(contract)
    try:
        actual = path.read_text(encoding="utf-8")
    except OSError:
        return f"missing generated runtime contract {path.relative_to(ROOT)}; run audit with --write"
    if actual != expected:
        return f"stale generated runtime contract {path.relative_to(ROOT)}; run audit with --write"
    return ""


def write_generated_contract(contract: dict[str, Any], path: Path = GENERATED_GDSCRIPT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_gdscript(contract), encoding="utf-8", newline="\n")


def _require_id(value: Any, label: str, failures: list[str]) -> str:
    if not isinstance(value, str) or not ID_PATTERN.fullmatch(value):
        failures.append(f"{label} must be lower_snake_case")
        return ""
    return value


def _require_id_list(value: Any, label: str, failures: list[str]) -> None:
    if not isinstance(value, list) or not value:
        failures.append(f"{label} must be a non-empty array")
        return
    for item in value:
        _require_id(item, label, failures)
    if len(value) != len(set(value)):
        failures.append(f"{label} must not contain duplicates")


def _positive_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value > 0


def _gd_dictionary(values: dict[str, int]) -> str:
    parts = [f'"{key}": {values[key]}' for key in sorted(values)]
    return "{" + ", ".join(parts) + "}"
