#!/usr/bin/env python3
"""Evaluate progression graph reachability, cycles, funding, and material floors."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from progression_graph import CANONICAL_CHAIN_IDS, Edge, Node, ProgressionGraph, ROOT
from progression_graph_contract import CANONICAL_EXTENSION_CHAINS


REVIEW_DOC_PATH = ROOT / "docs" / "current" / "PROGRESSION_GRAPH.md"


@dataclass(frozen=True)
class AuditResult:
    stages: dict[str, int]
    failures: tuple[str, ...]
    soft_annotations: tuple[str, ...]


def compute_stages(graph: ProgressionGraph, blocked: Iterable[str] = ()) -> dict[str, int]:
    blocked_keys = set(blocked)
    stages: dict[str, int] = {}
    for stage in range(len(graph.nodes) + 1):
        reached = set(stages)
        ready = [
            key
            for key in sorted(graph.nodes)
            if key not in reached and key not in blocked_keys and _can_reach(graph, key, reached)
        ]
        if not ready:
            break
        for key in ready:
            stages[key] = stage
    return stages


def audit_graph(graph: ProgressionGraph, *, check_canonical: bool = True) -> AuditResult:
    failures: list[str] = []
    failures.extend(_unresolved_failures(graph))
    failures.extend(_cycle_failures(graph))
    stages = compute_stages(graph)
    for node in sorted(graph.nodes.values(), key=lambda item: item.key):
        if node.mandatory and node.key not in stages:
            failures.append(f"Mandatory {node.label} ({node.key}) is unreachable from a fresh profile.")
    failures.extend(_funding_failures(graph))
    failures.extend(_material_floor_failures(graph))
    failures.extend(_guard_counter_failures(graph))
    if check_canonical:
        failures.extend(_canonical_order_failures(graph, stages))
    soft = tuple(
        f"{_label(graph, edge.source)} -> {_label(graph, edge.target)}: {edge.note or edge.relation}"
        for edge in graph.edges
        if edge.relation == "requires" and not edge.hard
    )
    return AuditResult(stages, tuple(dict.fromkeys(failures)), soft)


def render_review_doc(
    graph: ProgressionGraph,
    result: AuditResult,
    *,
    source_description: str = "`config/progression_contract.json` and `maps/production_slice_*.greybox.json`",
    audited_view_lines: Iterable[str] = (),
) -> str:
    view_lines = list(audited_view_lines)
    lines = [
        "# Cross-Map Progression Graph",
        "",
        f"Generated from {source_description}.",
        "Do not edit this file directly; run `python tools/audit_progression_graph.py --write`.",
        "",
        f"Status: **{'PASS' if not result.failures else 'FAIL'}**",
    ]
    if view_lines:
        lines.extend(["", "## Audited Views", "", *view_lines])
    lines.extend([
        "",
        "## Detailed Canonical View",
        "",
        "The table and dependency diagram below describe the promoted full-level view.",
        "",
        "### Deterministic Stages",
        "",
        "| Stage | Item / condition | Map / route | Blocker | Prerequisite source | Unlock / payoff | Reachability |",
        "| ---: | --- | --- | --- | --- | --- | --- |",
    ])
    report_nodes = [node for node in graph.nodes.values() if node.mandatory]
    report_nodes.sort(key=lambda node: (result.stages.get(node.key, 9999), node.map_id, node.kind, node.key))
    for node in report_nodes:
        stage = result.stages.get(node.key)
        requirements = _requirement_labels(graph, node.key)
        sources = _source_labels(graph, node)
        outcomes = _outcome_labels(graph, node.key)
        map_route = node.map_id or "global"
        if node.route:
            map_route += f" / {node.route}"
        lines.append(
            "| {stage} | `{item}` | {map_route} | {blocker} | {sources} | {outcomes} | {reachability} |".format(
                stage=stage if stage is not None else "-",
                item=node.label,
                map_route=_cell(map_route),
                blocker=_cell(", ".join(requirements) or "none"),
                sources=_cell(", ".join(sources) or "source-authored"),
                outcomes=_cell(", ".join(outcomes) or "state/payoff"),
                reachability=f"stage {stage}" if stage is not None else "UNREACHABLE",
            )
        )
    lines.extend(["", "## Soft Pressure Annotations", ""])
    if result.soft_annotations:
        lines.extend(f"- {annotation}" for annotation in result.soft_annotations)
    else:
        lines.append("- None in the current authored chain.")
    lines.extend(["", "## Dependency View", "", "```mermaid", "flowchart LR"])
    selected = _diagram_nodes(graph)
    aliases = {key: f"n{index}" for index, key in enumerate(sorted(selected))}
    groups: dict[str, list[str]] = {}
    for key in sorted(selected):
        node = graph.nodes[key]
        groups.setdefault(node.map_id or "global", []).append(key)
    for group, keys in sorted(groups.items()):
        lines.append(f'  subgraph {group.replace("-", "_")}["{_mermaid(group)}"]')
        for key in keys:
            node = graph.nodes[key]
            lines.append(f'    {aliases[key]}["{_mermaid(node.label)}"]')
        lines.append("  end")
    relations = {"requires", "unlocks", "guards", "rewards", "funds", "travels_to"}
    for edge in sorted(graph.edges, key=lambda item: (item.source, item.target, item.relation)):
        if edge.source in selected and edge.target in selected and edge.relation in relations:
            style = "-.->" if edge.relation == "requires" and not edge.hard else "-->"
            lines.append(f'  {aliases[edge.source]} {style}|"{edge.relation}"| {aliases[edge.target]}')
    lines.extend(["```", "", "## Diagnostics", ""])
    if result.failures:
        lines.extend(f"- FAIL: {failure}" for failure in result.failures)
    else:
        lines.append("- No unresolved IDs, hard cycles, self-gated materials, guard/counter inversions, unreachable mandatory nodes, or funding-floor failures.")
    return "\n".join(lines) + "\n"


def review_doc_failure(expected: str, path: Path = REVIEW_DOC_PATH) -> str:
    try:
        actual = path.read_text(encoding="utf-8")
    except OSError:
        return f"missing progression review doc {path.relative_to(ROOT)}; run audit with --write"
    if actual != expected:
        return f"stale progression review doc {path.relative_to(ROOT)}; run audit with --write"
    return ""


def write_review_doc(content: str, path: Path = REVIEW_DOC_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _can_reach(graph: ProgressionGraph, key: str, reached: set[str]) -> bool:
    node = graph.nodes[key]
    if node.kind == "map":
        if node.attrs.get("start") is True:
            return True
        return any(edge.source in reached for edge in graph.incoming(key, "travels_to"))
    if node.attrs.get("declaration_only") is True:
        return any(edge.source in reached for edge in graph.incoming(key, "unlocks"))
    requirements = graph.requirements(key)
    if any(edge.target not in graph.nodes or edge.target not in reached for edge in requirements):
        return False
    if node.kind == "material":
        return any(edge.source in reached and edge.quantity > 0 for edge in graph.incoming(key, "rewards"))
    if node.kind == "material_pool":
        candidates = node.attrs.get("candidate_keys", [])
        return sum(candidate in reached for candidate in candidates) >= int(node.attrs.get("select_count", 0))
    if node.kind == "project":
        for material_id, required in node.attrs.get("required_materials", {}).items():
            if _material_quantity(graph, f"material:{material_id}", reached) < int(required):
                return False
    if node.kind in {"upgrade", "capability"} and int(node.attrs.get("cost", 0)) > 0:
        funding = node.attrs.get("funding_keys", [])
        available = sum(
            int(graph.nodes[source].attrs.get("wallet_reward", 0))
            for source in funding
            if source in reached and source in graph.nodes
        )
        if node.attrs.get("funding_source_ids") and not all(source in reached for source in funding):
            return False
        return available >= int(node.attrs["cost"])
    return True


def _unresolved_failures(graph: ProgressionGraph) -> list[str]:
    failures: list[str] = []
    for edge in graph.edges:
        for endpoint, role in ((edge.source, "source"), (edge.target, "target")):
            if endpoint not in graph.nodes:
                failures.append(f"Unresolved {role} {endpoint!r} on {edge.relation} edge {edge.source!r} -> {edge.target!r}.")
    return failures


def _cycle_failures(graph: ProgressionGraph) -> list[str]:
    adjacency = {
        key: [edge.target for edge in graph.requirements(key) if edge.target in graph.nodes]
        for key in graph.nodes
    }
    failures: list[str] = []
    visiting: list[str] = []
    visited: set[str] = set()

    def visit(key: str) -> None:
        if key in visiting:
            cycle = visiting[visiting.index(key):] + [key]
            failures.append("Hard dependency cycle: " + " -> ".join(_label(graph, item) for item in cycle) + ".")
            return
        if key in visited:
            return
        visiting.append(key)
        for target in adjacency[key]:
            visit(target)
        visiting.pop()
        visited.add(key)

    for key in sorted(graph.nodes):
        visit(key)
    return failures


def _funding_failures(graph: ProgressionGraph) -> list[str]:
    failures: list[str] = []
    for node in graph.nodes.values():
        if node.attrs.get("mandatory") is not True or int(node.attrs.get("cost", 0)) <= 0:
            continue
        stages = compute_stages(graph, {node.key})
        funding = node.attrs.get("funding_keys", [])
        unresolved = [key for key in funding if key not in stages]
        if unresolved:
            failures.append(f"Mandatory purchase {node.label} has funding behind its own gate: {', '.join(_label(graph, key) for key in unresolved)}.")
        floor = sum(int(graph.nodes[key].attrs.get("wallet_reward", 0)) for key in funding if key in graph.nodes)
        if floor < int(node.attrs["cost"]):
            failures.append(f"Mandatory purchase {node.label} has guaranteed funding floor {floor}, below cost {node.attrs['cost']}.")
    return failures


def _material_floor_failures(graph: ProgressionGraph) -> list[str]:
    failures: list[str] = []
    for node in graph.nodes.values():
        if node.kind != "project":
            continue
        stages = compute_stages(graph, {node.key})
        reached = set(stages)
        for material_id, required in node.attrs.get("required_materials", {}).items():
            available = _material_quantity(graph, f"material:{material_id}", reached)
            if available < int(required):
                failures.append(
                    f"Project {node.label} requires {required} {material_id}, but only {available} guaranteed pre-project source quantity is reachable."
                )
    return failures


def _guard_counter_failures(graph: ProgressionGraph) -> list[str]:
    failures: list[str] = []
    for edge in graph.edges:
        if edge.relation != "guards" or edge.source not in graph.nodes or edge.target not in graph.nodes:
            continue
        defeat_key = next((req.target for req in graph.requirements(edge.target) if req.target.startswith("defeat:")), "")
        counter_key = next((req.target for req in graph.requirements(defeat_key) if req.note == "counter"), "") if defeat_key else ""
        if counter_key and (_depends_on(graph, counter_key, edge.target) or edge.target in graph.nodes[counter_key].attrs.get("funding_keys", [])):
            failures.append(f"Guarded target {_label(graph, edge.target)} is required to obtain its counter {_label(graph, counter_key)}.")
    return failures


def _canonical_order_failures(graph: ProgressionGraph, stages: dict[str, int]) -> list[str]:
    failures = _ordered_chain_failures(graph, stages, CANONICAL_CHAIN_IDS, "Canonical progression")
    for trigger_id, raw_ids in CANONICAL_EXTENSION_CHAINS:
        if graph.resolve(trigger_id) in graph.nodes:
            failures.extend(_ordered_chain_failures(graph, stages, raw_ids, "Canonical extension"))
    return failures


def _ordered_chain_failures(
    graph: ProgressionGraph, stages: dict[str, int], raw_ids: Iterable[str], label: str
) -> list[str]:
    failures: list[str] = []
    ordered: list[tuple[str, int]] = []
    for raw_id in raw_ids:
        key = graph.resolve(raw_id)
        if key not in graph.nodes:
            failures.append(f"{label} node {raw_id!r} is unresolved.")
        elif key not in stages:
            failures.append(f"{label} node {_label(graph, key)} is unreachable.")
        else:
            ordered.append((key, stages[key]))
    for (left, left_stage), (right, right_stage) in zip(ordered, ordered[1:]):
        if left_stage >= right_stage:
            failures.append(f"{label} order drift: {_label(graph, left)} (stage {left_stage}) must precede {_label(graph, right)} (stage {right_stage}).")
    return failures


def _depends_on(graph: ProgressionGraph, start: str, target: str) -> bool:
    pending = [start]
    visited: set[str] = set()
    while pending:
        key = pending.pop()
        if key == target:
            return True
        if key in visited or key not in graph.nodes:
            continue
        visited.add(key)
        pending.extend(edge.target for edge in graph.requirements(key))
    return False


def _material_quantity(graph: ProgressionGraph, material_key: str, reached: set[str]) -> int:
    return sum(edge.quantity for edge in graph.incoming(material_key, "rewards") if edge.source in reached)


def _requirement_labels(graph: ProgressionGraph, key: str) -> list[str]:
    node = graph.nodes[key]
    labels = [_label(graph, edge.target) for edge in graph.requirements(key) if graph.nodes.get(edge.target, Node("", edge.target, "")).kind != "map"]
    if int(node.attrs.get("cost", 0)) > 0:
        labels.append(f"wallet {node.attrs['cost']}")
    return labels


def _source_labels(graph: ProgressionGraph, node: Node) -> list[str]:
    if node.attrs.get("funding_keys"):
        return [_label(graph, key) for key in node.attrs["funding_keys"]]
    if node.kind == "material":
        return [_label(graph, edge.source) for edge in graph.incoming(node.key, "rewards")]
    return [_label(graph, edge.target) for edge in graph.requirements(node.key)][:3]


def _outcome_labels(graph: ProgressionGraph, key: str) -> list[str]:
    labels = [_label(graph, edge.target) for edge in graph.outgoing(key) if edge.relation in {"unlocks", "rewards", "travels_to", "guards"}]
    return list(dict.fromkeys(labels))[:3]


def _diagram_nodes(graph: ProgressionGraph) -> set[str]:
    selected = {node.key for node in graph.nodes.values() if node.mandatory or node.kind == "pressure"}
    for edge in graph.edges:
        if edge.source in selected and graph.nodes[edge.source].kind == "pressure" and edge.target in graph.nodes:
            selected.add(edge.target)
    return selected


def _label(graph: ProgressionGraph, key: str) -> str:
    return graph.nodes[key].label if key in graph.nodes else key


def _cell(value: str) -> str:
    return value.replace("|", "/").replace("\n", " ")


def _mermaid(value: str) -> str:
    return value.replace('"', "'").replace("\n", " ")
